version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"   # Spring Boot default
    volumes:
      - ./backend:/app
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    command: mvn spring-boot:run
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"   # Vite dev server
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mos
      POSTGRES_PASSWORD: mos
      POSTGRES_DB: mos
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
