-- V1__init.sql (Flyway)
-- no extension; ids generated by Hibernate/JPA

CREATE TABLE app_user (
  id            UUID PRIMARY KEY,
  email         VARCHAR(255) UNIQUE NOT NULL,
  display_name  VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE reminder (
  id         UUID PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  time_at    TIMESTAMPTZ NOT NULL,
  category   VARCHAR(40) NOT NULL,
  note       TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_reminder_user_id ON reminder(user_id);
CREATE INDEX idx_reminder_time_at ON reminder(time_at);

CREATE TABLE meal_requirement (
  id         UUID PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  type       VARCHAR(40) NOT NULL,
  notes      TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_mealreq_user_id ON meal_requirement(user_id);
