# spring:
#     datasource:
#     url: jdbc:h2:mem:testdb
#     driver-class-name: org.h2.Driver
#     username: sa
#     password: 
#   jpa:
#     hibernate:
#       ddl-auto: create-drop
#     properties:
#       hibernate.jdbc.time_zone: UTC
#   flyway:
#     enabled: false
#   h2:
#     console:
#       enabled: true
#     autoconfigure:
#     exclude: 
#       - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#       - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration