spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apl
    username: apl
    password: apl
  jpa:
    hibernate:
      ddl-auto: validate   # let Flyway own schema
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true