openapi: 3.0.1
info:
  title: MOS (Meal and Reminder System) API
  description: API for managing meal requirements, reminders, and user authentication
  version: 1.0.0
  contact:
    name: MOS Development Team
    email: dev@mos.example.com
servers:
- url: http://localhost:8080
  description: Development server
- url: https://api.mos.example.com
  description: Production server
paths:
  # Authentication endpoints
  /api/auth/login:
    post:
      tags:
      - authentication
      summary: User login
      description: Authenticate a user and return a JWT token
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
            example:
              email: "admin@mos.test"
              password: "password123"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
              example:
                token: "eyJhbGciOiJIUzUxMiJ9..."
                tokenType: "Bearer"
                userId: "550e8400-e29b-41d4-a716-446655440001"
                email: "admin@mos.test"
                displayName: "System Administrator"
                userType: "ADMIN"
                expiresAt: "2025-09-23T09:20:54Z"
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid email or password"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Validation failed"

  /api/auth/me:
    get:
      tags:
      - authentication
      summary: Get current user information
      description: Retrieve details of the authenticated user
      operationId: getCurrentUser
      security:
      - bearerAuth: []
      responses:
        "200":
          description: User information retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfoResponse"
              example:
                id: "550e8400-e29b-41d4-a716-446655440001"
                email: "admin@mos.test"
                displayName: "System Administrator"
                userType: "ADMIN"
                isActive: true
                createdAt: "2025-09-22T09:13:56.743059+00"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized"

  /api/auth/logout:
    post:
      tags:
      - authentication
      summary: User logout
      description: Logout the current user (client-side token invalidation)
      operationId: logout
      security:
      - bearerAuth: []
      responses:
        "200":
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Logout successful"
  /api/users/{userId}/reminders:
    get:
      tags:
      - reminders
      summary: Get user reminders
      description: Retrieve all reminders for a specific user
      operationId: getReminders
      security:
      - bearerAuth: []
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: User ID
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ReminderDto"
    post:
      tags:
      - reminders
      summary: Create a reminder
      description: "Create a new reminder with time, category, and optional note."
      operationId: createReminder
      security:
      - bearerAuth: []
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: User ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateReminderRequest"
        required: true
      responses:
        "400":
          description: Invalid input
          content:
            '*/*':
              schema:
                type: string
                example:
                  status: 400
                  error: Bad Request
                  message: time must be now or future (±5m)
                  path: /api/v1/reminders
        "201":
          description: Reminder created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ReminderDto"
  /api/users/{userId}/reminders/{reminderId}:
    put:
      tags:
      - reminders
      summary: Update a reminder
      description: Update an existing reminder with new time, category, or note
      operationId: updateReminder
      security:
      - bearerAuth: []
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: User ID
      - name: reminderId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: Reminder ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateReminderRequest"
            examples:
              updateOnceReminder:
                summary: Update a one-time reminder
                value:
                  type: "once"
                  category: "medicin"
                  dateTime: "2025-09-27T14:30:00Z"
                  note: "Updated medication reminder"
              updateRecurringReminder:
                summary: Update a recurring reminder
                value:
                  type: "recurring"
                  category: "måltider"
                  days: ["Mon", "Wed", "Fri"]
                  times: ["08:00", "12:00", "18:00"]
                  note: "Updated meal reminders"
              partialUpdate:
                summary: Partial update (only note)
                value:
                  note: "Just updating the note"
      responses:
        "200":
          description: Reminder updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReminderDto"
              example:
                id: "550e8400-e29b-41d4-a716-446655440001"
                time: "2025-09-27T14:30:00Z"
                category: "MEDICATION"
                note: "Updated medication reminder"
                createdAt: "2025-09-26T12:00:00Z"
                type: "once"
                recurrence: null
        "400":
          description: Invalid input or reminder not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Bad Request"
                  message:
                    type: string
                    example: "Reminder not found for user"
        "404":
          description: Reminder not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Not Found"
                  message:
                    type: string
                    example: "Reminder not found"
    delete:
      tags:
      - reminders
      summary: Delete a reminder
      description: Delete a specific reminder by ID
      operationId: deleteReminder
      security:
      - bearerAuth: []
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: User ID
      - name: reminderId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: Reminder ID
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
        "204":
          description: No Content

  /api/users/{userId}/meal-requirements:
    get:
      tags:
      - meal-requirements
      summary: Get user meal requirements
      description: Retrieve all meal requirements for a specific user
      operationId: getMealRequirements
      security:
      - bearerAuth: []
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: User ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MealRequirementsResponse"
    post:
      tags:
      - meal-requirements
      summary: Set meal requirements
      description: Set meal requirements for a user. Replaces all existing requirements.
      operationId: setMealRequirements
      security:
      - bearerAuth: []
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: User ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MealRequirementsRequest"
        required: true
      responses:
        "201":
          description: Meal requirements set successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MealRequirementsResponse"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /api/auth/login

  schemas:
    # Authentication schemas
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User email address
          example: "admin@mos.test"
        password:
          type: string
          format: password
          description: User password
          example: "password123"

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          description: JWT access token
          example: "eyJhbGciOiJIUzUxMiJ9..."
        tokenType:
          type: string
          description: Token type
          example: "Bearer"
        userId:
          type: string
          format: uuid
          description: User ID
          example: "550e8400-e29b-41d4-a716-446655440001"
        email:
          type: string
          format: email
          description: User email
          example: "admin@mos.test"
        displayName:
          type: string
          description: User display name
          example: "System Administrator"
        userType:
          type: string
          enum: [ADMIN, CAREGIVER, RESIDENT]
          description: User role
          example: "ADMIN"
        expiresAt:
          type: string
          format: date-time
          description: Token expiration time
          example: "2025-09-23T09:20:54Z"

    UserInfoResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: User ID
          example: "550e8400-e29b-41d4-a716-446655440001"
        email:
          type: string
          format: email
          description: User email
          example: "admin@mos.test"
        displayName:
          type: string
          description: User display name
          example: "System Administrator"
        userType:
          type: string
          enum: [ADMIN, CAREGIVER, RESIDENT]
          description: User role
          example: "ADMIN"
        isActive:
          type: boolean
          description: Whether user account is active
          example: true
        createdAt:
          type: string
          format: date-time
          description: Account creation timestamp
          example: "2025-09-22T09:13:56.743059+00"

    # User management schemas
    UserType:
      type: string
      enum: [ADMIN, CAREGIVER, RESIDENT]
      description: User role types

    # Reminder schemas
    CreateReminderRequest:
      type: object
      required:
        - type
        - category
        - dateTime
      properties:
        type:
          type: string
          description: Reminder type
          example: "måltider"
        category:
          type: string
          enum: [MEDICATION, MEAL]
          description: Reminder category
          example: "MEAL"
        dateTime:
          type: string
          format: date-time
          description: Reminder date and time
          example: "2025-09-22T12:00:00Z"
        note:
          type: string
          description: Optional note
          example: "Lunch reminder"

    UpdateReminderRequest:
      type: object
      description: Request body for updating a reminder (all fields optional for partial updates)
      properties:
        type:
          type: string
          enum: ["once", "recurring"]
          description: Reminder type
          example: "once"
        category:
          type: string
          description: Reminder category (Swedish or English)
          example: "medicin"
        dateTime:
          type: string
          format: date-time
          description: Reminder date and time (for once type)
          example: "2025-09-27T14:30:00Z"
        days:
          type: array
          items:
            type: string
          description: Days of the week for recurring reminders
          example: ["Mon", "Wed", "Fri"]
        times:
          type: array
          items:
            type: string
          description: Times for recurring reminders
          example: ["08:00", "12:00", "18:00"]
        note:
          type: string
          description: Optional note
          example: "Updated reminder note"

    ReminderDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Reminder ID
          example: "550e8400-e29b-41d4-a716-446655440001"
        time:
          type: string
          format: date-time
          description: Reminder time
          example: "2025-09-22T12:00:00Z"
        category:
          type: string
          enum: [MEDICATION, MEAL]
          description: Reminder category
          example: "MEAL"
        note:
          type: string
          description: Reminder note
          example: "Lunch reminder"
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
          example: "2025-09-22T09:13:56.743059+00"

    # Meal requirement schemas
    MealRequirementsRequest:
      type: object
      required:
        - requirements
      properties:
        requirements:
          type: array
          items:
            type: string
          example: ["Laktosfri", "Diabetesanpassad"]
    MealRequirementsResponse:
      type: object
      properties:
        requirements:
          type: array
          items:
            $ref: '#/components/schemas/MealRequirementDto'
    MealRequirementDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        requirement:
          type: string
        createdAt:
          type: string
          format: date-time

