name: CI (minimal tests)

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Backend tests (minimal suite)
        run: |
          cd backend
          chmod +x mvnw || true
          ./mvnw -q test -Dtest=MosApplicationTests,JwtUtilTest,ReminderServiceUpdateTest,AuthenticationServiceTest

      - name: Backend build
        run: |
          cd backend
          ./mvnw -q -DskipTests package

